### PR TITLE
add support for progressive override in federation

### PR DESCRIPTION
**Pull request by RomKadria**
hey, we use your lib and need support for the progressive override feature as seen here 
https://www.apollographql.com/docs/federation/entities-advanced/#incremental-migration-with-override

Thanks :)

### CODE REVIEW

**Review by hayes — COMMENTED** [review]
I think label needs to be optional, but otherwise this looks good! Can you also add a changesets?

**Review by hayes — APPROVED** [review]
Thanks!

**Comment by hayes** [comment]
Sorry, i probably should have been a little more specific.  This repo uses changesets to manage releases/versioning (instructions in the comment from the changesets bot above),  so we need to revert the change log entry and the version change, but add a changesets entry.  I can also do this myself later when I'm back at a computer

**Comment by RomKadria** [comment]
> Sorry, i probably should have been a little more specific. This repo uses changesets to manage releases/versioning (instructions in the comment from the changesets bot above), so we need to revert the change log entry and the version change, but add a changesets entry. I can also do this myself later when I'm back at a computer

Hey sorry didnt see it was away for a bit. Thanks so much!!!

**Pull request merged**
